import os
from os.path import join
import sys

sys.path.append(".")
from pkg.io import files_match_pattern

"""
This is a full pre-processing workflow for MSI data (provided as .imzML or .d).

input:
    data folder must contain the following directories:
    - "msi": directory with .imzML files or .d directories named group_sampleno.imzML/.d

output:
    sub-directories will be created for each pre-processing step containing the processed data
    along with quality control visualizations.
"""


configfile: 'data/config.yaml'


msi_pattern = r"^[a-zA-z0-9]+_[a-zA-z0-9]+\.(imzML|d)$" # imzML files must be named: condition_sampleno.imzML


SCRIPT_PATH = os.path.join('msi_preprocessing_flow', 'scripts')
SEGMENTATION_SCRIPT_PATH = os.path.join(SCRIPT_PATH, '../..', 'msi_segmentation_flow/scripts')
ANALYSIS_SCRIPT_PATH = os.path.join(SCRIPT_PATH, '../..', 'region_group_analysis_flow/scripts')
VIS_SCRIPT_PATH = os.path.join(SCRIPT_PATH, '../..', 'data_visualization')
DATA_PATH = config['data']

# BENCHMARK_PATH = join(DATA_PATH, 'benchmark')
# BM_REPEAT = 5
INPUT_DIR = join(DATA_PATH, 'msi')
OUT_DIR = join(DATA_PATH, 'msi')
FILES = files_match_pattern(INPUT_DIR, msi_pattern)
FILES = [f.split('.')[0] for f in FILES]
EXT = [f.split('.')[1] for f in os.listdir(INPUT_DIR) if f.endswith('.d') or f.endswith('.imzML')][0]
#print('found {} files. \n processing files: {}'.format(len(FILES), FILES))
MASS_LIST = [float(item) for item in config['general']['mass_list'].split(',')]

if config['matrix_removal']['matrix_mzs']:
    ruleorder: get_matrix_img_list > single_sample_segmentation
else:
    ruleorder: single_sample_segmentation > get_matrix_img_list
if config['matrix_removal']['clustering']:
    ruleorder: single_sample_segmentation > get_matrix_img_list


# Custom function to calculate resources based on file size
def file_size_resources(wildcards, input_file):
    # Get the file size in bytes
    file_size = os.path.getsize(input_file)

    # Convert file size to MB
    file_size_mb = file_size / (1024 * 1024)

    # Define the resources based on file size
    mem_mb_needed = file_size_mb * 10

    return {"mem_mb": mem_mb_needed}


def get_pipeline_paths(out_dir, files, mass_list):
    snr = config['peak_picking']['snr']
    perc = config['alignment']['pixel_percentage']
    paths = {}

    # Stage 0: base peakpicking
    base = f"{out_dir}/peakpicking_{snr}snr"
    paths['base'] = base

    # Stage 1: calibration
    if config['general']['calibration']:
        base_cal = f"{base}/calibration"
    else:
        base_cal = base
    paths['calibration'] = base_cal

    # Stage 2: alignment
    base_align = f"{base_cal}/alignment_{perc}pxperc"
    paths['alignment'] = base_align

    # Stage 3: matrix removal
    if config['general']['matrix_removal']:
        base_matrix = f"{base_align}/matrix_removal"
    else:
        base_matrix = base_align
    paths['matrix_removal'] = base_matrix

    # Stage 4: peak filtering
    if config['general']['peak_filtering']:
        base_filtered = f"{base_matrix}/{config['peak_filtering']['thr']}sc_filtered"
    else:
        base_filtered = base_matrix
    paths['peak_filtering'] = base_filtered

    # Stage 5: intranorm
    if config['general']['norm']:
        # intranorm
        base_intranorm = f"{base_filtered}/intranorm_{config['intranorm']['method']}"
        # inter-norm
        base_internorm = f"{base_intranorm}/internorm_{config['internorm']['method']}"
    else:
        base_intranorm = base_filtered
        base_internorm = base_filtered
    paths['intranorm'] = base_intranorm
    paths['internorm'] = base_internorm
    paths['median_spectrum'] = f"{base_intranorm}/median_spectrum.npy"

    # Stage 6: outlier removal
    if config['general']['outlier_removal']:
        base_outlier = f"{base_internorm}/outlier_removal"
    else:
        base_outlier = base_internorm
    paths['outlier_removal'] = base_outlier

    # Stage 7: deisotoping
    if config['general']['deisotoping']:
        base_deiso = f"{base_outlier}/deisotoped"
    else:
        base_deiso = base_outlier
    paths['deisotoped'] = base_deiso
    paths['deiso_mz'] = f"{base_deiso}/deiso_mz.npy"

    # Stage 8: summarized CSV
    paths['summarized_csv'] = f"{base_deiso}/summarized/summarized.csv"

    # Stage 9: imzML and ome.tif
    paths['imzml'] = expand(f"{base_deiso}/{{fl}}.imzML", fl=files)
    paths['ometif'] = expand(f"{base_deiso}/{{fl}}.ome.tif", fl=files)

    # QC deviation images
    if mass_list:
        paths['deviation_images'] = expand(
            f"{out_dir}/peakpicking_{snr}snr/quality_control/deviation_to_{{mass}}.png",
            mass=mass_list
        )

    # single-sample segmentation for matrix removal
    if not config['matrix_removal']['matrix_mzs']:
        seg_path = f"{base_align}/{config['matrix_removal']['dim_reduction']}"
        if config['matrix_removal']['dim_reduction'] == 'umap':
            seg_path += (f"{config['matrix_removal']['umap_params']['n_neighbors']}neighb_"
                         f"{config['matrix_removal']['cluster_algorithm']}")
        if config['matrix_removal']['cluster_algorithm'] == 'hdbscan':
            seg_path += (f"_{config['matrix_removal']['hdbscan_params']['min_samples']}ms_"
                         f"{config['matrix_removal']['hdbscan_params']['min_cluster_size']}mcs")
    else:
        seg_path = base_align
    paths['segmentation_single_sample'] = seg_path

    # multi-sample segmentation for outlier detection
    paths['segmentation_multi_sample'] = (
        f"{base_internorm}/umap_"
        f"{config['outlier_detection']['umap_params']['n_neighbors']}neighb_"
        f"hdbscan_"
        f"{config['outlier_detection']['hdbscan_params']['min_cluster_size']}mcs_"
        f"{config['outlier_detection']['hdbscan_params']['min_samples']}ms"
    )

    return paths

def get_input(out_dir, files, mass_list, input_list=[]):
    paths = get_pipeline_paths(out_dir, files, mass_list)
    # QC deviation images
    if mass_list:
        input_list.append(paths['deviation_images'])
    # median spectrum for MFC inter-normalisation
    if config['general']['norm'] and len(files) > 1 and config['internorm']['method'] == 'mfc':
        input_list.append(paths['median_spectrum'])
    # deisotoped m/z vector
    if config['general']['deisotoping']:
        input_list.append(paths['deiso_mz'])
    # summarized CSV
    input_list.append(paths['summarized_csv'])
    # pre-processed imzML
    input_list.append(paths['imzml'])
    # ome.tif with ion images of peaks
    input_list.append(paths['ometif'])

    return input_list


if config['internorm']['method'] == 'mfc':
    ruleorder: internorm_mfc > internorm
else:
    ruleorder: internorm > internorm_mfc


rule all:
    input: get_input(OUT_DIR, FILES, MASS_LIST)
    #input: expand(OUT_DIR + '/peakpicking_' + str(config['peak_picking']['snr']) + 'snr/{fl}.imzML', fl=FILES)
    #input: expand(OUT_DIR + '/peakpicking_' + str(config['peak_picking']['snr']) + 'snr/alignment_' + str(config['alignment']['pixel_percentage']) + 'pxperc/{fl}.imzML', fl=FILES)

rule peak_picking:
    input: INPUT_DIR + '/{fl}.' + EXT
    output: get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['base'] + '/{fl}.imzML'
    # benchmark: repeat(BENCHMARK_PATH + "/{fl}.peak_picking.benchmark.txt", BM_REPEAT)
    shell: 'python ' + SCRIPT_PATH + '/peak_picking/peak_picking.py {input:q} -snr {config[peak_picking][snr]} \
            -window_size {config[peak_picking][window]} -order {config[peak_picking][order]} -smooth {config[peak_picking][smooth]} \
            -out_dir ' + get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['base'] + ' -mass_list {config[general][mass_list]}'

rule deviation_to_mass:
    input: imzML_files = expand(get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['base'] + '/{fl}.imzML', fl=FILES)
    output: get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['deviation_images']
    shell: 'python ' + SCRIPT_PATH + '/qc/deviation_to_mass.py {config[general][mass_list]} ' + get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['base'] +
            ' -result_dir ' + get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['base'] + '/quality_control'

rule calibration:
    input: get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['base'] + '/{fl}.imzML'
    output: get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['calibration'] + '/{fl}.imzML'
    shell: 'python ' + SCRIPT_PATH + '/alignment/alignment.py {input} -calibrate 1 -result_dir ' + get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['calibration'] +
           ' -mass_list {config[general][mass_list]} -max_shift {config[alignment][max_shift]} -unit {config[alignment][unit]}'

rule get_reference_spectrum:
   input: expand(get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['calibration'] + '/{fl}.imzML', fl=FILES)
   output: get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['alignment'] + '/cmz.npy'
   # benchmark: repeat(BENCHMARK_PATH + "/get_reference_spectrum.benchmark.txt", BM_REPEAT)
   shell: 'python ' + SCRIPT_PATH + '/alignment/get_reference_spectrum.py ' + get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['calibration'] + ' -result_dir ' + get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['alignment'] + ' -mz_res {config[alignment][mz_resolution]} -px_perc {config[alignment][pixel_percentage]} -num_px_perc {config[alignment][num_pixel_percentage]} -mass_list {config[general][mass_list]}'

rule alignment:
    input: file = get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['calibration'] + '/{fl}.imzML',
           reference = get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['alignment'] + '/cmz.npy'
    output: get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['alignment'] + '/{fl}.imzML'
    # benchmark: repeat(BENCHMARK_PATH + "/{fl}.alignment.benchmark.txt", BM_REPEAT)
    shell: 'python ' + SCRIPT_PATH + '/alignment/alignment.py {input.file} -refmz {input.reference} -result_dir ' + get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['alignment'] + ' -mass_list {config[general][mass_list]} -max_shift {config[alignment][max_shift]} -unit {config[alignment][unit]}'

rule single_sample_segmentation:
    input: get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['alignment'] + '/{fl}.imzML'
    output: get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['segmentation_single_sample'] + '/binary_imgs/{fl}_matrix_cluster.tif'
    resources:
        mem_mb=lambda wildcards: file_size_resources(wildcards,input_file=get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['alignment']+"/{}.ibd".format(wildcards.fl))["mem_mb"]
    # benchmark: repeat(BENCHMARK_PATH + "/{fl}.single_sample_segmentation.benchmark.txt", BM_REPEAT)
    shell: 'python ' + SEGMENTATION_SCRIPT_PATH + '/single_sample_segmentation.py {input:q} \
            -result_dir ' + get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['segmentation_single_sample'] + ' -method {config[matrix_removal][dim_reduction]} -n_components {config[matrix_removal][n_components]}'
            ' -metric {config[matrix_removal][umap_params][metric]} -n_neighbors {config[matrix_removal][umap_params][n_neighbors]}'
            ' -min_dist {config[matrix_removal][umap_params][min_dist]} -n_clusters {config[matrix_removal][kmeans_params][n_clusters]}'
            ' -min_cluster_size {config[matrix_removal][hdbscan_params][min_cluster_size]} -min_samples {config[matrix_removal][hdbscan_params][min_samples]}'
            ' -matrix_cluster True -cluster {config[matrix_removal][cluster_algorithm]}'

rule get_matrix_img_list:
    input: get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['alignment'] + '/{fl}.imzML'
    output: get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['segmentation_single_sample'] + '/binary_imgs/{fl}_matrix_cluster.tif'
    shell: 'python ' + SCRIPT_PATH + '/matrix_removal/get_matrix_pixels_from_mz_list.py {input} '
            '{config[matrix_removal][matrix_mzs]} -result_dir ' + get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['segmentation_single_sample'] + '/binary_imgs '
            '-threshold {config[matrix_removal][thr_method]}'

rule get_matrix_pixels:
    input: imzML_file = get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['alignment'] + '/{fl}.imzML',
            matrix_img = get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['segmentation_single_sample'] + '/binary_imgs/{fl}_matrix_cluster.tif'
    output: get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['matrix_removal'] + '/{fl}_extended_matrix_image.tif'
    # benchmark: repeat(BENCHMARK_PATH + "/{fl}.get_matrix_pixels.benchmark.txt", BM_REPEAT)
    shell: 'python ' + SCRIPT_PATH + '/matrix_removal/get_matrix_pixels_from_segmentation.py {input.imzML_file} '
            + get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['segmentation_single_sample'] + '/binary_imgs/ -result_dir ' + get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['matrix_removal']
            + ' -matrix_corr_thr {config[matrix_removal][matrix_corr_thr]} -pixel_perc_thr {config[matrix_removal][pixel_perc_thr]}'

rule matrix_removal:
    input: imzML_file = get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['alignment'] + '/{fl}.imzML',
            extended_matrix_img = get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['matrix_removal'] + '/{fl}_extended_matrix_image.tif'
    output: get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['matrix_removal'] + '/{fl}.imzML'
    # benchmark: repeat(BENCHMARK_PATH + "/{fl}.matrix_removal.benchmark.txt", BM_REPEAT)
    shell: 'python ' + SCRIPT_PATH + '/matrix_removal/matrix_removal.py {input.imzML_file:q} {input.extended_matrix_img:q} '
            '-proc_matrix_img {config[matrix_removal][matrix_postproc]} -pixel_removal {config[matrix_removal][pixel_removal]}'
            ' -matrix_subtraction {config[matrix_removal][matrix_subtraction]}'
            ' -matrix_peaks_removal {config[matrix_removal][matrix_peak_removal]}'
            ' -num_matrix_peaks {config[matrix_removal][num_matrix_peaks]}'

rule calc_spatial_coherence:
    input: get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['matrix_removal'] + '/{fl}.imzML'
    output: get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['matrix_removal'] + '/{fl}_sc.csv'
    # benchmark: repeat(BENCHMARK_PATH + "/{fl}.calc_spatial_coherence.benchmark.txt", BM_REPEAT)
    shell: 'python ' + SCRIPT_PATH + '/peak_filtering/spatial_coherence.py {input:q} -result_dir ' + get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['matrix_removal']

rule sum_spatial_coherence:
    input: sc_files = expand(get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['matrix_removal'] + '/{fl}_sc.csv', fl=FILES),
           imzML_files = expand(get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['matrix_removal'] + '/{fl}.imzML', fl=FILES)
    output: get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['matrix_removal'] + '/peaks_above_' + str(config['peak_filtering']['thr']) + 'sc.npy'
    # benchmark: repeat(BENCHMARK_PATH + "/sum_spatial_coherence.benchmark.txt", BM_REPEAT)
    shell: 'python ' + SCRIPT_PATH + '/peak_filtering/get_mzs_above_spatial_coherence_thr.py ' + get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['matrix_removal']
            + ' -thr ' + str(config['peak_filtering']['thr']) + ' -sum ' + str(config['peak_filtering']['sum'])

rule filter_spatial_coherence:
    input: imzML_file = get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['matrix_removal'] + '/{fl}.imzML',
           sc_thr_file = get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['matrix_removal'] + '/peaks_above_' + str(config['peak_filtering']['thr']) + 'sc.npy'
    output: get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['peak_filtering'] + '/{fl}.imzML'
    # benchmark: repeat(BENCHMARK_PATH + "/{fl}.filter_spatial_coherence.benchmark.txt", BM_REPEAT)
    shell: 'python ' + SCRIPT_PATH + '/peak_filtering/filter_spatial_coherence.py {input.imzML_file} {config[peak_filtering][thr]} {input.sc_thr_file} -result_dir ' + get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['peak_filtering']

rule intranorm:
    input: get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['peak_filtering'] + '/{fl}.imzML'
    output: get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['intranorm'] + '/{fl}.imzML'
    # benchmark: repeat(BENCHMARK_PATH + "/{fl}.intranorm.benchmark.txt", BM_REPEAT)
    shell: 'python ' + SCRIPT_PATH + '/intranorm/intranorm.py {input:q} -result_dir ' + get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['intranorm'] + ' -method {config[intranorm][method]}'

rule median_spectrum:
    input: expand(get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['intranorm'] + '/{fl}.imzML', fl=FILES)
    output: get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['median_spectrum']
    # benchmark: repeat(BENCHMARK_PATH + "/median_spectrum.benchmark.txt", BM_REPEAT)
    shell: 'python ' + SCRIPT_PATH + '/internorm/get_median_overall_spectrum.py ' + get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['intranorm'] + ' {output:q}'

rule internorm_mfc:
    input: file = get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['intranorm'] + '/{fl}.imzML',
            reference = rules.median_spectrum.output
    output: get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['internorm'] + '/{fl}.imzML'
    # benchmark: repeat(BENCHMARK_PATH + "/{fl}.internorm.benchmark.txt", BM_REPEAT)
    shell: 'python ' + SCRIPT_PATH + '/internorm/internorm.py {input.file:q} -result_dir ' \
           + get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['internorm'] + ' -method {config[internorm][method]} -reference {input.reference:q}'

rule internorm:
    input: get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['intranorm'] + '/{fl}.imzML'
    output: get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['internorm'] + '/{fl}.imzML'
    # benchmark: repeat(BENCHMARK_PATH + "/{fl}.internorm.benchmark.txt", BM_REPEAT)
    shell: 'python ' + SCRIPT_PATH + '/internorm/internorm.py {input.file:q} -result_dir ' \
           + get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['internorm'] + '\' -method {config[internorm][method]}'

rule multi_sample_segmentation:
    input: expand(get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['internorm'] + '/{fl}.imzML', fl=FILES)
    #output: seg_imgs = get_io_path_multi_sample_segmentation()[1]  + '/{fl}.png',
    #        umap_data = get_io_path_multi_sample_segmentation()[1] + '/umap_data.csv'
    output: umap_data = get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['segmentation_multi_sample'] + '/umap_data.csv'
    # benchmark: repeat(BENCHMARK_PATH + "/multi_sample_segmentation.benchmark.txt", BM_REPEAT)
    shell: 'python ' + SEGMENTATION_SCRIPT_PATH + '/multi_sample_segmentation.py ' + get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['internorm']
            + ' -result_dir ' + get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['segmentation_multi_sample']
            + ' -n_neighbors {config[outlier_detection][umap_params][n_neighbors]}'
            ' -min_cluster_size {config[outlier_detection][hdbscan_params][min_cluster_size]}'
            ' -min_samples {config[outlier_detection][hdbscan_params][min_samples]}'

rule outlier_detection:
    input: umap_data = rules.multi_sample_segmentation.output.umap_data,
            imzML_files = expand(get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['internorm'] + '/{fl}.imzML', fl=FILES)
    output: expand(get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['outlier_removal'] + '/{fl}.imzML', fl=FILES)
    # benchmark: repeat(BENCHMARK_PATH + "/outlier_detection.benchmark.txt", BM_REPEAT)
    shell: 'python ' + SCRIPT_PATH + '/outlier_detection/umap_outlier_detection.py {input.umap_data} '
            + get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['internorm'] + ' -result_dir ' + get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['outlier_removal']
            + ' -cluster_thr {config[outlier_detection][cluster_thr]} -sample_thr {config[outlier_detection][sample_thr]}'
              ' -remove_ssc {config[outlier_detection][remove_ssc]}'

rule get_deisotoped_mz:
    input: expand(get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['outlier_removal'] + '/{fl}.imzML', fl=FILES)
    output: get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['deiso_mz']
    # benchmark: repeat(BENCHMARK_PATH + "/get_deisotoped_mz.benchmark.txt", BM_REPEAT)
    shell: 'python ' + SCRIPT_PATH + '/deisotoping/get_deisotoped_mz.py ' + get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['outlier_removal'] +
            ' -result_dir ' + get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['deisotoped'] +
            ' -tolerance {config[deisotoping][tolerance]} -min_isotopes {config[deisotoping][min_isotopes]} \
            -max_isotopes {config[deisotoping][max_isotopes]} -openMS {config[deisotoping][openMS]}'

rule deisotoping:
    input: reference = get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['deiso_mz'],
            file = get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['outlier_removal'] + '/{fl}.imzML'
    output: get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['deisotoped'] + '/{fl}.imzML'
    # benchmark: repeat(BENCHMARK_PATH + "/{fl}.deisotoping.benchmark.txt", BM_REPEAT)
    shell: 'python ' + SCRIPT_PATH + '/deisotoping/deisotope.py {input.file:q} {input.reference:q} \
            -result_dir ' + get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['deisotoped']

rule summarize:
    input: expand(get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['deisotoped'] + '/{fl}.imzML', fl=FILES)
    output: get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['summarized_csv']
    shell: 'python ' + ANALYSIS_SCRIPT_PATH + '/get_summarized_spectra.py ' + get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['deisotoped']
            + ' -result_dir ' + get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['deisotoped'] + '/summarized -qc True'

rule ion_image_stack:
    input: get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['deisotoped'] + '/{fl}.imzML'
    output: get_pipeline_paths(OUT_DIR, FILES, MASS_LIST)['deisotoped'] + '/{fl}.ome.tif'
    shell: 'python ' + VIS_SCRIPT_PATH + '/generate_mz_tif_stack.py {input} {output}'

# rule get_matrix_pixels_list:
#     input: get_path_for_matrixsub(OUT_DIR) + '/{fl}.imzML'
#     output: coords = get_path_for_matrixsub(OUT_DIR) + '/matrix_subtraction/{fl}_matrix_pixels.csv',
#             img = get_path_for_matrixsub(OUT_DIR) + '/matrix_subtraction/{fl}_matrix_cluster.tif'
#     shell: 'python ' + SCRIPT_PATH + '/get_matrix_pixels_from_mz_list.py {input:q} \
#             {config[matrixsub][mz]} -result_dir \'' + get_path_for_matrixsub(OUT_DIR) + '/matrix_subtraction\''
#
# rule matrix_subtraction:
#     input: imzml = get_path_for_matrixsub(OUT_DIR) + '/{fl}.imzML',
#            matrix_pixel = get_path_for_matrixsub(OUT_DIR) + '/matrix_subtraction/{fl}_matrix_pixels.csv'
#     output: get_path_for_matrixsub(OUT_DIR) + '/matrix_subtraction/{fl}.imzML'
#     shell: 'python ' + SCRIPT_PATH + '/matrix_removal.py {input.imzml:q} {input.matrix_pixel:q} \
#             -result_dir \'' + get_path_for_matrixsub(OUT_DIR) + '/matrix_subtraction\' \
#             -pixel_removal {config[matrixsub][pixel_removal]} -matrix_subtraction {config[matrixsub][matrix_subtraction]}'
#
# rule get_region_imzML:
#     input: get_path_for_region(OUT_DIR) + '/{fl}.imzML'
#     output: get_path_for_region(OUT_DIR) + '/' + config['region']['name'] + '/{fl}.imzML'
#     shell: 'python ' + SCRIPT_PATH + '/get_region_imzML_from_mask.py {input:1} \'{config[region][bin_dir]}/{wildcards.fl}.tif\' \
#              -result_dir \'' + get_path_for_region(OUT_DIR) + '/' + config['region']['name'] + '\''
#
#
#
# rule transformation:
#     input: get_path_for_transform(OUT_DIR, FILES) + '/{fl}.imzML'
#     output: get_path_for_transform(OUT_DIR, FILES) + '/transformation/{fl}.imzML'
#     shell: 'python ' + SCRIPT_PATH + '/transformation.py {input:q} -result_dir \'' + \
#            get_path_for_transform(OUT_DIR,FILES) + '/transformation\''
#
# rule get_spatial_coherence:
#     input: get_path_for_spatial_coherence(OUT_DIR, FILES) + '/{fl}.imzML'
#     output: get_path_for_spatial_coherence(OUT_DIR, FILES) + '/spatial_coherence/{fl}_sc.csv'
#     shell: 'python ' + SCRIPT_PATH + '/spatial_coherence.py {input:q} ' + \
#             get_path_for_spatial_coherence(OUT_DIR, FILES) + '/spatial_coherence'
#
# rule get_mzs_above_spatial_coherence_thr:
#     input: get_input_for_filter_spatial_coherence(OUT_DIR, FILES)[1]
#     output: get_input_for_filter_spatial_coherence(OUT_DIR, FILES)[0] + '/peaks_above_sc.npy'
#     shell: 'python ' + SCRIPT_PATH + '/get_mzs_above_spatial_coherence_thr.py \'' + \
#             get_input_for_filter_spatial_coherence(OUT_DIR, FILES)[0] + '\' \'' + \
#            get_path_for_spatial_coherence(OUT_DIR,FILES) + '\' \'' +
#            get_input_for_filter_spatial_coherence(OUT_DIR, FILES)[0] + '\' -thr {config[spatial_coherence][thr]}'
#
# rule filter_spatial_coherence:
#     input: imzML=get_path_for_spatial_coherence(OUT_DIR, FILES) + '/{fl}.imzML',
#             refmz=get_input_for_filter_spatial_coherence(OUT_DIR, FILES)[0] + '/peaks_above_sc.npy'
#     output: get_path_for_spatial_coherence(OUT_DIR, FILES) + '/spatial_coherence/{fl}.imzML'
#     shell: 'python ' + SCRIPT_PATH + '/filter_spatial_coherence.py {input.imzML:q} {input.refmz:q} \'' + \
#             get_input_for_filter_spatial_coherence(OUT_DIR, FILES)[0] + '\''
#
# rule get_summarized_spectra:
#     input: get_input_for_summarized(OUT_DIR, FILES)[1]
#     output: get_input_for_summarized(OUT_DIR, FILES)[0] + '/summarized/summarized.csv'
#     shell: 'python ' + SCRIPT_PATH + '/get_summarized_spectra.py \'' + get_input_for_summarized(OUT_DIR, FILES)[0] + '\' \
#             -result_dir \'' + get_input_for_summarized(OUT_DIR, FILES)[0] + '/summarized